a=int(input("enter a number"))
b=int(input("enter a second number"))
operator=int(input("enter a operator"))
if(operator="sum")
 print("the sum",a+b)
elif(operator="sub")
print("the sub",a-b)
elif(operator="mul")
print("the mul",a*b)
elif(operator ="div")
print(the div",a/b)
else
print("invalid ")
